# -*- coding: utf-8 -*-
"""colab_diabetes_hba1c_pycaret.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QWb9g_ifUj7BBw4yeyVueqZdlu2CXkff
"""

# Installation and Setup

# Install required packages
!pip install pycaret==3.3.2
!pip install catboost
!pip install psutil

import pandas as pd
import numpy as np
import os
import warnings
warnings.filterwarnings('ignore')

# System configuration modules
import psutil
import multiprocessing as mp

# Check PyCaret version
from pycaret.utils import version
print("PyCaret version:")
version()

"""# 1. System Configuration"""

def get_system_config():
    """Adaptive configuration based on system resources"""
    cores = mp.cpu_count()
    ram_gb = round(psutil.virtual_memory().total / (1024**3))

    print(f"🔧 System Config: {cores} cores, {ram_gb}GB RAM")

    if cores >= 8 and ram_gb >= 16:
        config = {
            'n_jobs': min(cores - 2, 16),
            'fold': 10,
            'train_size': 0.8,
            'transformation': True,
            'remove_outliers': False,  # Keep clinical edge cases
            'outliers_threshold': 0.01,  # Very conservative
            'multicollinearity_threshold': 0.95,  # Less aggressive
            'feature_selection': True,
            'feature_selection_threshold': 0.8
        }
        print("📊 High-performance configuration loaded")
    elif cores >= 4 and ram_gb >= 8:
        config = {
            'n_jobs': min(cores - 1, 8),
            'fold': 5,
            'train_size': 0.8,
            'transformation': True,
            'remove_outliers': False,
            'outliers_threshold': 0.02,
            'multicollinearity_threshold': 0.9,
            'feature_selection': True,
            'feature_selection_threshold': 0.8
        }
        print("📊 Standard configuration loaded")
    else:
        config = {
            'n_jobs': 2,
            'fold': 5,
            'train_size': 0.8,
            'transformation': False,
            'remove_outliers': False,
            'multicollinearity_threshold': 0.85,
            'feature_selection': False
        }
        print("📊 Basic configuration loaded")

    return config

# Initialize system configuration
cfg = get_system_config()
print(f"📊 Using: n_jobs={cfg['n_jobs']}, fold={cfg['fold']}")

"""# 2. Data Loading"""

def load_diabetes_dataset():
    """Load the most complete diabetes dataset"""
    print("🔍 Searching for diabetes datasets...")

    base_paths = ['./final_imputed_data/', 'final_imputed_data/', './']
    dataset_files = [
        'nmbfinalDiabetes (4)_selected_columns_cleaned_processed_final_imputed.csv',
        'nmbfinalnewDiabetes (3)_selected_columns_cleaned_processed_final_imputed.csv',
        'PrePostFinal (3)_selected_columns_cleaned_processed_final_imputed.csv'
    ]

    target_column = 'PostBLHBA1C'

    for file in dataset_files:
        for bp in base_paths:
            path = os.path.join(bp, file)
            if os.path.exists(path):
                df = pd.read_csv(path)
                if target_column in df.columns:
                    # Clean target variable
                    initial_rows = len(df)
                    df = df.dropna(subset=[target_column])

                    # Remove extreme outliers only (>4 standard deviations)
                    mean_val = df[target_column].mean()
                    std_val = df[target_column].std()
                    z_scores = np.abs((df[target_column] - mean_val) / std_val)
                    df = df[z_scores <= 4]

                    print(f"✅ Loaded: {file}")
                    print(f"📊 Shape: {df.shape} (removed {initial_rows - len(df)} outliers)")
                    print(f"📈 HbA1c range: {df[target_column].min():.2f} - {df[target_column].max():.2f}")
                    print(f"📊 HbA1c mean ± std: {df[target_column].mean():.2f} ± {df[target_column].std():.2f}")

                    return df, target_column

    raise FileNotFoundError("❌ No suitable diabetes dataset found!")

# Load the dataset
data, target = load_diabetes_dataset()

# Display basic information
print(f"\n📋 Dataset Overview:")
print(f"Rows: {data.shape[0]}, Columns: {data.shape[1]}")
print(f"Target: {target}")
print(f"Missing values: {data.isnull().sum().sum()}")

# Show first few rows
data.head(3)

"""# 3. Advanced Feature Engineering"""

def create_medical_features(df, target_col):
    """Create advanced features for HbA1c prediction using medical domain knowledge"""
    print("🧬 Starting Advanced Feature Engineering...")
    df_enhanced = df.copy()

    # Separate numeric and categorical features
    numeric_cols = df_enhanced.select_dtypes(include=[np.number]).columns.tolist()
    if target_col in numeric_cols:
        numeric_cols.remove(target_col)

    print(f"📊 Found {len(numeric_cols)} numeric features for enhancement")

    # 1. Create Medical Risk Scores
    if len(numeric_cols) >= 3:
        print("🏥 Creating diabetes risk composite scores...")
        # Find features most correlated with HbA1c
        correlations = df_enhanced[numeric_cols].corrwith(df_enhanced[target_col]).abs()
        top_features = correlations.nlargest(5).index

        for i, feat in enumerate(top_features[:3]):
            df_enhanced[f'diabetes_risk_score_{i+1}'] = df_enhanced[feat]

    # 2. Statistical Interactions for Top Predictors
    print("🔬 Creating feature interactions...")
    corr_with_target = df_enhanced[numeric_cols].corrwith(df_enhanced[target_col]).abs()
    high_corr_features = corr_with_target[corr_with_target > 0.2].index.tolist()

    if len(high_corr_features) >= 2:
        for i, feat1 in enumerate(high_corr_features[:3]):
            for feat2 in high_corr_features[i+1:4]:
                # Multiplicative interaction
                df_enhanced[f'{feat1}_x_{feat2}'] = df_enhanced[feat1] * df_enhanced[feat2]

                # Ratio interaction (clinical ratios are important)
                denominator = df_enhanced[feat2].replace(0, 1e-8)
                df_enhanced[f'{feat1}_div_{feat2}'] = df_enhanced[feat1] / denominator

    # 3. Non-linear Transformations for Top Features
    print("📈 Creating non-linear transformations...")
    for feat in high_corr_features[:3]:
        df_enhanced[f'{feat}_squared'] = df_enhanced[feat] ** 2
        df_enhanced[f'{feat}_sqrt'] = np.sqrt(np.abs(df_enhanced[feat]))
        df_enhanced[f'{feat}_log1p'] = np.log1p(np.abs(df_enhanced[feat]))

    # 4. Statistical Aggregate Features
    print("📊 Creating statistical aggregates...")
    current_numeric = df_enhanced.select_dtypes(include=[np.number]).columns
    if target_col in current_numeric:
        current_numeric = current_numeric.drop(target_col)

    if len(current_numeric) > 0:
        df_enhanced['feature_mean'] = df_enhanced[current_numeric].mean(axis=1)
        df_enhanced['feature_std'] = df_enhanced[current_numeric].std(axis=1)
        df_enhanced['feature_max'] = df_enhanced[current_numeric].max(axis=1)
        df_enhanced['feature_min'] = df_enhanced[current_numeric].min(axis=1)
        df_enhanced['feature_range'] = df_enhanced['feature_max'] - df_enhanced['feature_min']

    # 5. Clean up infinite and NaN values
    print("🧹 Cleaning enhanced features...")
    df_enhanced = df_enhanced.replace([np.inf, -np.inf], np.nan)

    # Corrected line to fill NaNs only in numeric columns
    df_enhanced = df_enhanced.fillna(df_enhanced.median(numeric_only=True))

    features_added = df_enhanced.shape[1] - df.shape[1]
    print(f"✨ Feature Engineering Complete!")
    print(f"📈 Features: {df.shape[1]} → {df_enhanced.shape[1]} (+{features_added} new features)")

    return df_enhanced

# Apply advanced feature engineering
enhanced_data = create_medical_features(data, target)

import re
from pycaret.regression import *

"""# 4. Setting up PyCaret Environment"""

# 🧹 Clean column names BEFORE setup to ensure compatibility with all models
# This removes forbidden characters like '[', ']', or '<' for XGBoost
enhanced_data.columns = [re.sub(r"[\[\]<]", "", col) for col in enhanced_data.columns]


print("🚀 Setting up PyCaret AutoML Environment...")
print("⚙️ Configuring advanced preprocessing pipeline...")

# Setup PyCaret with optimized configuration for medical data
regression_exp = setup(
    data=enhanced_data,
    target=target,
    session_id=42,

    # Data splitting
    train_size=cfg['train_size'],
    fold=cfg['fold'],
    fold_strategy='kfold',

    # Preprocessing pipeline
    numeric_imputation='mean',
    categorical_imputation='mode',
    normalize=True,
    transformation=cfg['transformation'],
    transformation_method='quantile',  # Better for non-normal distributions

    # Feature selection (conservative for medical data)
    remove_multicollinearity=True,
    multicollinearity_threshold=cfg['multicollinearity_threshold'],
    feature_selection=cfg['feature_selection'],
    n_features_to_select=cfg.get('feature_selection_threshold', 0.8),

    # Outlier handling (very conservative for clinical data)
    remove_outliers=cfg['remove_outliers'],
    outliers_threshold=cfg.get('outliers_threshold', 0.02),

    # System optimization
    n_jobs=cfg['n_jobs'],

    # ❗️ CORRECTED PARAMETER NAME ❗️
    verbose=False
)

print("✅ PyCaret environment setup complete!")

"""# 5. Compare High-Performance Models"""

print("🏆 Comparing High-Performance Models for HbA1c Prediction...")

# Select only high-performance models (removing poor performers like Random Forest)
high_performance_models = [
    'catboost',     # Usually best for tabular data
    'xgboost',      # Excellent gradient boosting
    'lightgbm',     # Fast and accurate
    'gbr',          # Scikit-learn gradient boosting
    'et',           # Extra trees (ensemble)
    'huber',        # Robust to outliers (good for medical data)
    'br'            # Bayesian ridge (good baseline)
]

print(f"🔍 Testing {len(high_performance_models)} algorithms optimized for tabular medical data...")

# Compare models - optimized for MAE (Mean Absolute Error)
model_comparison = compare_models(
    include=high_performance_models,
    sort='MAE',          # Optimize for MAE (most important for clinical accuracy)
    n_select=5,          # Select top 5 models
    fold=cfg['fold'],
    round=4,
    verbose=False
)

print("✅ Model comparison completed!")
model_comparison

"""# 6. Hyperparameter Tuning"""

print("⚡ Hyperparameter Tuning Top 3 Models...")
print("🎯 Optimizing specifically for MAE < 0.5 target...")

# Tune top 3 models for maximum performance
tuned_models = []

for i, model in enumerate(model_comparison[:3]):
    model_name = str(model).split('(')[0]
    print(f"🔧 Tuning Model {i+1}/3: {model_name}")

    try:
        # Intensive hyperparameter tuning
        tuned_model = tune_model(
            model,
            optimize='MAE',
            n_iter=50 if cfg['n_jobs'] > 4 else 30,  # More iterations for better systems
            fold=cfg['fold'],
            choose_better=True,
            verbose=False
        )
        tuned_models.append(tuned_model)
        print(f"  ✅ {model_name} tuning completed")

    except Exception as e:
        print(f"  ⚠️ {model_name} tuning failed, using base model: {str(e)[:50]}...")
        tuned_models.append(model)

print("🎉 All hyperparameter tuning completed!")

"""# 7. Create Model"""

# Individual model creation for specific algorithms
print("🔨 Creating individual optimized models...")

# Create best individual models
catboost_model = create_model('catboost', verbose=True)
print("✅ CatBoost model created")

xgboost_model = create_model('xgboost', verbose=True)
print("✅ XGBoost model created")

lightgbm_model = create_model('lightgbm', verbose=True)
print("✅ LightGBM model created")

"""# 8. Ensemble Models"""

print("🎯 Creating Advanced Ensemble Models...")

# Method 1: Blending (Soft Voting / Weighted Average)
print("🔄 Creating Blended Ensemble...")
try:
    blended_ensemble = blend_models(
        estimator_list=tuned_models,
        optimize='MAE',
        fold=cfg['fold'],
        weights=None,  # Auto-optimize weights
        choose_better=True,
        verbose=False
    )
    print("✅ Blended ensemble created successfully")
except Exception as e:
    print(f"⚠️ Blending failed: {e}")
    blended_ensemble = tuned_models[0]  # Fallback to best single model

# Method 2: Stacking with Ridge Meta-Learner (Signature Approach)
print("🏗️ Creating Stacked Ensemble with Ridge Meta-Learner...")
try:
    stacked_ensemble = stack_models(
        estimator_list=tuned_models[:3],  # Top 3 base learners
        meta_model=create_model('ridge'),  # Ridge regression as meta-learner
        fold=cfg['fold'],
        restack=True,  # Use out-of-fold predictions
        optimize='MAE',
        choose_better=True,
        verbose=False
    )
    print("✅ Stacked ensemble created successfully")
except Exception as e:
    print(f"⚠️ Stacking failed: {e}")
    stacked_ensemble = blended_ensemble  # Fallback to blended model

"""# 9. Analyze Models"""

print("📊 Comprehensive Model Analysis...")

# Define models for evaluation
models_to_analyze = {
    'Best_Single_Model': tuned_models[0],
    'Blended_Ensemble': blended_ensemble,
    'Stacked_Ridge_Ensemble': stacked_ensemble
}

# Performance evaluation
results_summary = []

for model_name, model in models_to_analyze.items():
    print(f"\n🎯 Analyzing {model_name}...")

    try:
        # Get holdout predictions
        predictions_df = predict_model(model, verbose=False)
        y_true = predictions_df[target]
        y_pred = predictions_df['prediction_label']

        # Calculate comprehensive metrics
        mae = np.mean(np.abs(y_true - y_pred))
        rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))
        r2 = np.corrcoef(y_true, y_pred)[0, 1] ** 2

        # Clinical accuracy assessment
        target_achieved = "🎯 YES" if mae < 0.5 else "❌ NO"
        clinical_accuracy = "Excellent" if mae <= 0.5 else "Good" if mae <= 1.0 else "Needs Improvement"

        results_summary.append({
            'Model': model_name,
            'MAE': round(mae, 4),
            'RMSE': round(rmse, 4),
            'R²': round(r2, 4),
            'Target_Achieved': target_achieved,
            'Clinical_Accuracy': clinical_accuracy
        })

        print(f"  📈 MAE: {mae:.4f} | RMSE: {rmse:.4f} | R²: {r2:.4f}")
        print(f"  🏥 Clinical Accuracy: {clinical_accuracy}")

        if mae < 0.5:
            print(f"  🎯 SUCCESS: Target MAE < 0.5 ACHIEVED!")
        else:
            improvement_needed = ((mae / 0.5 - 1) * 100)
            print(f"  📊 Need {improvement_needed:.1f}% improvement for clinical target")

    except Exception as e:
        print(f"  ❌ Analysis failed: {e}")
        results_summary.append({
            'Model': model_name,
            'MAE': 'Error',
            'RMSE': 'Error',
            'R²': 'Error',
            'Target_Achieved': '❌ Error',
            'Clinical_Accuracy': 'Error'
        })

# Display comprehensive results
print("\n" + "="*80)
print("🏆 COMPREHENSIVE MODEL PERFORMANCE ANALYSIS")
print("="*80)

results_df = pd.DataFrame(results_summary)
print(results_df.to_string(index=False))

"""# 10. Model Visualization"""

print("📊 Creating Model Visualizations...")

# Find best performing model
valid_results = [r for r in results_summary if isinstance(r['MAE'], (int, float))]
if valid_results:
    best_result = min(valid_results, key=lambda x: x['MAE'])
    best_model_name = best_result['Model']
    best_model = models_to_analyze[best_model_name]

    print(f"🥇 Best Model: {best_model_name} (MAE: {best_result['MAE']})")

    # Plot model performance
    try:
        print("📈 Generating residuals plot...")
        plot_model(best_model, plot='residuals', save=True)

        print("📊 Generating prediction error plot...")
        plot_model(best_model, plot='error', save=True)

        print("🎯 Generating feature importance plot...")
        plot_model(best_model, plot='feature', save=True)

        print("✅ All visualization plots saved successfully")

    except Exception as e:
        print(f"⚠️ Some visualizations failed: {e}")

"""# 11. Interpret Model"""

print("🔍 Model Interpretation and Feature Analysis...")

try:
    # Feature importance interpretation
    if hasattr(best_model, 'feature_importances_') or hasattr(best_model, 'coef_'):
        print("📊 Feature importance analysis available")

        # Additional interpretation plots
        try:
            interpret_model(best_model)
            print("✅ Model interpretation completed")
        except:
            print("ℹ️ Advanced interpretation not available for this model type")
    else:
        print("ℹ️ Feature importance not directly available for ensemble models")

except Exception as e:
    print(f"⚠️ Model interpretation failed: {e}")

"""# 12. Finalize and Save Model"""

print("💾 Finalizing and Saving Best Model...")

try:
    # Finalize the best model (trains on full dataset)
    final_model = finalize_model(best_model)

    # Save the model
    model_filename = f'hba1c_prediction_model_{best_model_name.lower()}'
    save_model(final_model, model_filename)

    print(f"✅ Model finalized and saved as '{model_filename}.pkl'")
    print(f"🎯 Best MAE achieved: {best_result['MAE']}")

    if best_result['MAE'] < 0.5:
        print("🎉 SUCCESS: Clinical target MAE < 0.5 ACHIEVED!")
        print("🏥 Model ready for clinical validation and deployment")
    else:
        print("📈 Model shows strong performance, consider additional optimization")

except Exception as e:
    print(f"❌ Model saving failed: {e}")

"""# 13. Clinical Summary"""

print("\n" + "="*80)
print("🏥 CLINICAL DIABETES MANAGEMENT MODEL SUMMARY")
print("="*80)

print(f"""
📋 Model Performance Summary:
   • Best Model: {best_model_name}
   • Mean Absolute Error: {best_result['MAE']} HbA1c units
   • Clinical Accuracy: {best_result['Clinical_Accuracy']}
   • R² Score: {best_result['R²']}

🎯 Clinical Target Analysis:
   • Target: MAE < 0.5 for clinical accuracy
   • Status: {best_result['Target_Achieved']}

🔬 Technical Approach:
   • Advanced feature engineering with medical domain knowledge
   • High-performance algorithms (CatBoost, XGBoost, LightGBM)
   • Ensemble methods (Blending + Stacking)
   • Conservative outlier handling for clinical data
   • Hyperparameter optimization for MAE minimization

📊 Model Architecture:
   • Base Learners: {len(tuned_models)} tuned high-performance models
   • Meta-Learner: Ridge Regression (for stability)
   • Cross-Validation: {cfg['fold']}-fold validation
   • Features: {enhanced_data.shape[1]} enhanced features

💡 Next Steps:
   1. Clinical validation with healthcare professionals
   2. Integration with diabetes management systems
   3. Continuous monitoring and model updates
   4. Regulatory compliance assessment
""")

print("="*80)
print("🎉 PyCaret HbA1c Prediction Model Development Complete!")
print("="*80)